[workspace]
resolver = "2"

members = [
    "emergence_game",
    "emergence_lib",
    "emergence_macros",
    "tools/ci",
    "tools/debug_tools",
]
default-members = ["emergence_game", "emergence_lib"]
