# Adopted from bevy
# See <https://github.com/bevyengine/bevy/blob/main/deny.toml>

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = [
  "RUSTSEC-2020-0056", # from cpal v0.14.1 - unmaintained - https://github.com/koute/stdweb/issues/403
]

[licenses]
unlicensed = "deny"
copyleft = "deny"
allow = [
  "MIT",
  "MIT-0",
  "Apache-2.0",
  "0BSD",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "ISC",
  "Zlib",
  "CC0-1.0",
  "OFL-1.1",
]
exceptions = [
  { name = "unicode-ident", allow = ["Unicode-DFS-2016"] },
  # For `bevy_egui`
  { name = "epaint", allow = ["LicenseRef-UFL-1.0"] },
]
default = "deny"

[bans]
multiple-versions = "warn"
# TODO: Change back to "deny"
# This currently doesn't work with git dependencies (even if the hash is fixed)
# See <https://github.com/Leafwing-Studios/Emergence/issues/193>
wildcards = "warn"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# If you add something here please also add a comment explaining why it's necessary :)
allow-git = [
  # hexx: waiting on a release for Bevy 0.10
  "https://github.com/ManevilleF/hexx", 
  # bevy_mod_picking: waiting on PR merge plus release for Bevy 0.10
  "https://github.com/soerenmeier/bevy_mod_raycast"
]
