# Adopted from bevy
# See <https://github.com/bevyengine/bevy/blob/main/deny.toml>

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = []

[licenses]
unlicensed = "deny"
copyleft = "deny"
allow = [
  "MIT",
  "MIT-0",
  "Apache-2.0",
  "0BSD",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "ISC",
  "Zlib",
  "CC0-1.0",
  "OFL-1.1",
]
exceptions = [
  { name = "unicode-ident", allow = ["Unicode-DFS-2016"] },
  # For `bevy_egui`
  { name = "epaint", allow = ["LicenseRef-UFL-1.0"] },
]
default = "deny"

[bans]
multiple-versions = "deny"
# TODO: Change back to "deny"
# This currently doesn't work with git dependencies (even if the hash is fixed)
# See <https://github.com/Leafwing-Studios/Emergence/issues/193>
wildcards = "warn"
highlight = "all"
# Certain crates/versions that will be skipped when doing duplicate detection.
skip = [
  { name = "concurrent-queue", version = "1.2.4" },    # from bevy_tasks v0.9.1
  { name = "ahash", version = "0.7.6" },               # from bevy_utils v0.9.1
  { name = "windows", version = "0.43.0" }, # from gilrs v 0.5.2
  { name = "core-foundation-sys", version = "0.6.2" }, # from cpal v 0.15
  { name = "redox_syscall", version = "0.2.0" }, # from bevy_asset v 0.10
  { name = "num-rational", version = "0.4.1" }, # from bevy_egui v0.18.0
  { name = "png", version = "0.16.8" },         # from bevy_egui v0.18.0
  { name = "nix", version = "0.24.3" },         # from alsa v0.7.0
  { name = "xml-rs", version = "0.8.4" }
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# If you add something here please also add a comment explaining why it's necessary :)
allow-git = [
  # hexx: waiting on a release for Bevy 0.10
  "https://github.com/ManevilleF/hexx", 
  # bevy_mod_picking: waiting on PR merge plus release for Bevy 0.10
  "https://github.com/soerenmeier/bevy_mod_raycast"
]
