# Adopted from bevy
# See <https://github.com/bevyengine/bevy/blob/main/deny.toml>

[licenses]
unlicensed = "deny"
copyleft = "deny"
allow = [
  "MIT",
  "MIT-0",
  "Apache-2.0",
  "BSD-3-Clause",
  "ISC",
  "Zlib",
  "0BSD",
  "BSD-2-Clause",
  "CC0-1.0",
  "BSL-1.0",
]
exceptions = [{ name = "unicode-ident", allow = ["Unicode-DFS-2016"] }]
default = "deny"
