//! Code for managing the map between terrain position and entity

use crate::simulation::map_data::MapResource;
use bevy::prelude::{Entity, Resource};

/// Helper for managing the mapping between a tile position and the terrain entity associated with
/// that position
///
/// It is generated by [`generate_terrain`](crate::simulation::generation::generate_terrain).
#[derive(Resource, Default)]
pub struct TerrainEntityMap {
    pub inner: MapResource<Entity>,
}
