[package]
name = "emergence_lib"
version = "0.1.0"
authors = ["Alice Cecile <alice.i.cecile@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8"
bevy_ecs_tilemap = { git = "https://github.com/StarArawn/bevy_ecs_tilemap", branch = "main"}
bevy_pancam = "0.6"
rand = "0.8"
indexmap = "1.9"
dashmap = "5.4"
leafwing-input-manager = "0.6.1"
emergence_macros = { path = "../emergence_macros" }

[dev-dependencies]
# We need headless operation in tests
bevy_ecs_tilemap = { git = "https://github.com/StarArawn/bevy_ecs_tilemap", branch = "main", default-features = false}
