[package]
name = "emergence_lib"
version = "0.1.0"
authors = ["Alice Cecile <alice.i.cecile@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9"
bevy_ecs_tilemap = { git = "https://github.com/StarArawn/bevy_ecs_tilemap", branch = "main" }
bevy_egui = "0.17.0"
bevy_pancam = "0.7"
debug_tools = { path = "../tools/debug" }
rand = "0.8"
leafwing-input-manager = "0.7"
emergence_macros = { path = "../emergence_macros" }
bevy-trait-query = { git = "https://github.com/Leafwing-Studios/bevy-trait-query", rev = "65533bf8680753a3f998056e1719b826652f3b69" }
indexmap = "1.9"

[dev-dependencies]
# We need headless operation in tests
bevy_ecs_tilemap = { git = "https://github.com/StarArawn/bevy_ecs_tilemap", branch = "main", default-features = false }
