# Adopted from Bevy
# See <https://github.com/bevyengine/bevy/blob/main/.github/workflows/dependencies.yml>

name: Dependencies

on:
  pull_request:
    paths:
      - "**/Cargo.toml"
      - "deny.toml"
  push:
    paths:
      - "**/Cargo.toml"
      - "deny.toml"
    branches-ignore:
      - "dependabot/**"
      - staging-squash-merge.tmp
  schedule:
    - cron: "0 0 * * 0"

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  check-advisories:
    name: Check advisories
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-deny
        run: cargo install cargo-deny
      - name: Check for security advisories and unmaintained crates
        run: cargo deny check advisories

  check-bans:
    name: Check bans
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-deny
        run: cargo install cargo-deny
      - name: Check for banned and duplicated dependencies
        run: cargo deny check bans

  check-licenses:
    name: Check licenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-deny
        run: cargo install cargo-deny
      - name: Check for unauthorized licenses
        run: cargo deny check licenses

  check-sources:
    name: Check sources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-deny
        run: cargo install cargo-deny
      - name: Checked for unauthorized crate sources
        run: cargo deny check sources
